#!/bin/bash
if [[ $(grep -E "^(ID|NAME)=" /etc/os-release | grep -qi "ubuntu"; echo $?) -ne 0 ]]; then
    echo "This setup script is intended for Ubuntu. Exiting."
    exit 1
fi

# create directories
export XDG_CONFIG_HOME="$HOME"/.config
mkdir -p "$XDG_CONFIG_HOME"/bash

# create symbolic links
ln -sf "$PWD/.bashrc" "$HOME"/.bashrc
ln -sf "$PWD/.bash_profile" "$HOME"/.bash_profile
ln -sf "$PWD/.bash_aliases" "$HOME"/.bash_aliases
ln -sf "$PWD/.inputrc" "$HOME"/.inputrc
ln -sf "$PWD/.tmux.conf" "$HOME"/.tmux.conf

# fonts
mkdir -p $HOME/.local/share/fonts
cp $PWD/fonts/UbuntuMono* $HOME/.local/share/fonts
